# Conteúdo das 5 landing pages da EcoClima.
# Textos das seções originais vêm de lp.ecoclimaregiao.online (Lovable).
# Campos novos para SEO/Índice de Qualidade: title, meta, sobre_*, faqs extras.

EMPRESA = {
    "nome": "EcoClima",
    "slogan": "Soluções Inteligentes em Ar Condicionado",
    "telefone": "(83) 3576-8662",
    "telefone_e164": "+558335768662",
    "rua": "Av. Manoel Teotônio dos Santos, 190",
    "cidade": "João Pessoa",
    "uf": "PB",
    "horario": "Seg a Sáb — 08h às 18h",
    "crm": "https://crm.altusflow.com.br/t/mumn10pv2e2k",
    "gtm": "GTM-MNQM2444",
}

PAGINAS = [
    {
        "slug": "servicos/instalacao",
        "keyword": "instalação de ar condicionado",
        "nome_curto": "Instalação",
        "servico_schema": "Instalação de ar condicionado",
        "title": "Instalação de Ar Condicionado em João Pessoa | EcoClima",
        "meta": "Instalação de ar condicionado em João Pessoa com equipe especializada, tubulação de cobre, vácuo e garantia. Visita técnica gratuita. Peça orçamento no WhatsApp.",
        "imagem": "instalacao-ar-condicionado-joao-pessoa",
        "img_ratio": (1080, 1440),
        "img_alt": "Técnico da EcoClima fazendo instalação de ar condicionado split em João Pessoa",
        "tagline": "Instalação profissional",
        "headline": "Instalação de ar condicionado especializada em João Pessoa",
        "sub": "Instalação de ar condicionado residencial e comercial em João Pessoa e região, com equipe especializada, acabamento profissional e garantia.",
        "pains": [
            "Medo de chamar alguém despreparado e estragar o aparelho novo",
            "Acabamento feio, com tubulação aparente e mal fixada",
            "Dúvida sobre a capacidade (BTUs) ideal para o seu ambiente",
            "Receio de ficar sem garantia de fábrica por instalação incorreta",
            "Vazamentos, ruídos e baixa eficiência por falta de vácuo correto",
        ],
        "benefits": [
            "Equipe técnica autorizada e certificada",
            "Tubulação de cobre de alta qualidade",
            "Acabamento limpo, discreto e profissional",
            "Vácuo e teste de pressão obrigatórios",
            "Mantemos a garantia de fábrica do equipamento",
            "Suporte pós-instalação sempre que precisar",
        ],
        "steps": [
            ("Visita técnica", "Avaliamos o local, indicamos a melhor posição e a capacidade ideal do equipamento — gratuito."),
            ("Instalação completa", "Realizamos infraestrutura, fixação e ligação elétrica seguindo todas as normas técnicas."),
            ("Testes e entrega", "Testamos o funcionamento, orientamos o uso e entregamos tudo limpo e organizado."),
        ],
        "guarantee": "Toda instalação realizada pela EcoClima inclui garantia formal sobre o serviço, manutenção da garantia de fábrica do equipamento e suporte técnico sempre que você precisar.",
        "testimonials": [
            ("Mariana S.", "Manaíra, João Pessoa", "Instalaram meu split em menos de 2 horas, com acabamento perfeito. Super recomendo!"),
            ("Rafael T.", "Tambaú, João Pessoa", "Equipe pontual e muito caprichosa. Não ficou um fio à mostra."),
            ("Juliana M.", "Cabo Branco, João Pessoa", "Me ajudaram a escolher a capacidade certa. Resultado impecável."),
        ],
        "sobre_titulo": "Instalação de ar condicionado split, cassete e multi-split",
        "sobre": [
            "A instalação de ar condicionado define quanto o aparelho vai gelar, quanto vai gastar de energia e quanto tempo vai durar. Por isso, a EcoClima começa pela visita técnica: medimos o ambiente, conferimos a rede elétrica e indicamos a capacidade em BTUs e a posição certa da evaporadora e da condensadora.",
            "Instalamos ar condicionado split hi-wall, cassete, piso-teto e multi-split em casas, apartamentos, lojas e escritórios de João Pessoa e região metropolitana. Usamos tubulação de cobre, fazemos vácuo e teste de pressão em toda instalação e deixamos o acabamento limpo, para você manter a garantia de fábrica do equipamento.",
        ],
        "faqs": [
            ("Quanto tempo demora a instalação?", "Em média de 2 a 4 horas para um split comum. Multi-split e cassete podem levar mais tempo dependendo da infraestrutura."),
            ("Vocês fornecem o material?", "Sim. Trabalhamos com tubulação de cobre, suportes, fios e acessórios de alta qualidade. Tudo já entra no orçamento, sem surpresas."),
            ("A instalação tem garantia?", "Sim. Oferecemos garantia formal sobre todo o serviço de instalação, e mantemos a garantia de fábrica do seu equipamento."),
            ("Atendem fora de João Pessoa?", "Sim, atendemos toda a região metropolitana de João Pessoa. Confirme a sua localidade pelo WhatsApp."),
            ("Como funciona o orçamento?", "Gratuito e sem compromisso. Basta enviar o modelo do aparelho e fotos do local pelo WhatsApp para uma estimativa rápida."),
        ],
    },
    {
        "slug": "servicos/manutencao",
        "keyword": "manutenção de ar condicionado",
        "nome_curto": "Manutenção",
        "servico_schema": "Manutenção de ar condicionado",
        "title": "Manutenção de Ar Condicionado em João Pessoa | EcoClima",
        "meta": "Manutenção de ar condicionado preventiva e corretiva em João Pessoa: higienização, checagem de gás e componentes, relatório técnico e garantia. Orçamento no WhatsApp.",
        "imagem": "manutencao-ar-condicionado-joao-pessoa",
        "img_ratio": (1080, 1080),
        "img_alt": "Técnico da EcoClima fazendo manutenção de ar condicionado em João Pessoa",
        "tagline": "Manutenção preventiva",
        "headline": "Manutenção de ar condicionado em João Pessoa",
        "sub": "Manutenção especializada e limpeza de ar condicionado em João Pessoa e região, com avaliação técnica e garantia do serviço.",
        "pains": [
            "Ar saindo com cheiro ruim ou causando alergias e tosse",
            "Conta de luz subindo sem explicação aparente",
            "Aparelho gelando pouco ou demorando a refrigerar",
            "Barulhos estranhos, gotejamento ou vazamento de água",
            "Falta de tempo para lembrar quando foi a última manutenção",
        ],
        "benefits": [
            "Limpeza profunda da evaporadora e condensadora",
            "Verificação de gás, pressão e componentes elétricos",
            "Maior vida útil do equipamento",
            "Funcionamento mais eficiente do equipamento",
            "Ar mais puro, livre de fungos, ácaros e bactérias",
            "Detecção precoce de problemas antes que virem prejuízo",
        ],
        "steps": [
            ("Diagnóstico", "Inspecionamos o equipamento e identificamos o nível de manutenção necessário."),
            ("Higienização completa", "Limpeza química, troca de filtros e verificação de todos os componentes internos."),
            ("Relatório e garantia", "Entregamos relatório técnico, garantia do serviço e agendamento da próxima revisão."),
        ],
        "guarantee": "Se em até 30 dias após a manutenção o aparelho apresentar qualquer problema relacionado ao serviço, voltamos sem custo adicional para resolver.",
        "testimonials": [
            ("Carlos R.", "Bancários, João Pessoa", "Manutenção rápida e preço justo. Meu split voltou a gelar como novo."),
            ("Patrícia L.", "Altiplano, João Pessoa", "Sou cliente há 3 anos. A equipe sempre explica o serviço e deixa o ambiente organizado."),
            ("André B.", "Jardim Oceania, João Pessoa", "O ar do quarto da minha filha não causa mais alergia. Diferença enorme!"),
        ],
        "sobre_titulo": "Manutenção preventiva e corretiva de ar condicionado",
        "sobre": [
            "A manutenção de ar condicionado mantém o aparelho gelando como deveria, evita defeitos caros e melhora a qualidade do ar que você respira. Na manutenção preventiva da EcoClima fazemos a higienização da evaporadora e da condensadora, a limpeza dos filtros e a checagem de gás, pressão e componentes elétricos.",
            "Quando o aparelho já apresenta falha, a manutenção corretiva identifica a causa e resolve. Atendemos residências e empresas em João Pessoa e região, com relatório técnico do que foi feito e o agendamento da próxima revisão, para você não precisar lembrar sozinho.",
        ],
        "faqs": [
            ("De quanto em quanto tempo devo fazer manutenção?", "Recomendamos a cada 6 meses para uso residencial e a cada 3 meses para uso comercial intenso."),
            ("Quanto tempo demora a manutenção?", "Em média 1 a 2 horas por aparelho, dependendo do estado do equipamento e do tipo de limpeza."),
            ("A manutenção ajuda no consumo de energia?", "Um aparelho limpo e funcionando corretamente tende a trabalhar com mais eficiência. O resultado depende do equipamento, uso e instalação."),
            ("Vocês usam produtos seguros?", "Sim. Utilizamos produtos químicos específicos, biodegradáveis e seguros para crianças, idosos e pets."),
            ("Tem garantia no serviço?", "Sim. Toda manutenção tem garantia formal e relatório técnico do que foi feito."),
        ],
    },
    {
        "slug": "servicos/limpeza",
        "keyword": "limpeza de ar condicionado",
        "nome_curto": "Limpeza",
        "servico_schema": "Limpeza de ar condicionado",
        "title": "Limpeza de Ar Condicionado em João Pessoa | EcoClima",
        "meta": "Limpeza de ar condicionado em João Pessoa: higienização de filtros e componentes, proteção do ambiente e teste final. Residencial e comercial. Orçamento no WhatsApp.",
        "imagem": "limpeza-ar-condicionado-joao-pessoa",
        "img_ratio": (960, 960),
        "img_alt": "Limpeza de ar condicionado split feita pela EcoClima em João Pessoa",
        "tagline": "Higienização especializada",
        "headline": "Limpeza de ar condicionado em João Pessoa",
        "sub": "Higienização especializada de filtros e componentes para melhorar o funcionamento do aparelho e a qualidade do ar em João Pessoa e região.",
        "pains": [
            "Cheiro ruim ao ligar o aparelho",
            "Filtros com poeira e sujeira acumulada",
            "Ar condicionado gelando menos",
            "Gotejamento ou ruídos durante o uso",
            "Muito tempo desde a última higienização",
        ],
        "benefits": [
            "Limpeza de filtros e componentes internos",
            "Proteção do ambiente durante o serviço",
            "Verificação do funcionamento do aparelho",
            "Atendimento residencial e comercial",
            "Equipe especializada em João Pessoa",
            "Garantia do serviço realizado",
        ],
        "steps": [
            ("Avaliação do aparelho", "Verificamos o estado do equipamento e definimos o procedimento adequado."),
            ("Limpeza especializada", "Protegemos o ambiente e higienizamos filtros e componentes acessíveis."),
            ("Teste final", "Montamos o equipamento e conferimos seu funcionamento antes da entrega."),
        ],
        "guarantee": "A limpeza é executada por equipe especializada, com proteção do ambiente, teste de funcionamento e garantia do serviço realizado.",
        "testimonials": [
            ("Carlos R.", "Bancários, João Pessoa", "A limpeza foi cuidadosa e o aparelho voltou a funcionar muito melhor."),
            ("Ana P.", "Tambaú, João Pessoa", "Equipe organizada, protegeu o ambiente e deixou tudo limpo ao terminar."),
            ("Marcos L.", "Bessa, João Pessoa", "Atendimento rápido e explicação clara sobre a situação do ar condicionado."),
        ],
        "sobre_titulo": "Limpeza e higienização de ar condicionado no local",
        "sobre": [
            "A limpeza de ar condicionado remove a poeira, o mofo e as bactérias que se acumulam nos filtros, na serpentina e na bandeja do aparelho. É isso que causa o cheiro ruim ao ligar, a queda no rendimento e, muitas vezes, as crises de alergia de quem fica no ambiente.",
            "A EcoClima faz a higienização do ar condicionado split no próprio local: protegemos móveis e paredes, higienizamos filtros e componentes, montamos o aparelho de volta e testamos o funcionamento antes de ir embora. Atendemos casas, apartamentos e empresas em João Pessoa e região.",
        ],
        "faqs": [
            ("Quando fazer a limpeza do ar condicionado?", "A frequência depende do ambiente e do uso. A equipe avalia o aparelho e orienta o intervalo adequado."),
            ("A limpeza é feita no local?", "Sim. O procedimento é realizado no local com proteção do ambiente."),
            ("Vocês atendem empresas?", "Sim. Atendemos residências e empresas em João Pessoa e região."),
            ("Quanto tempo demora?", "O tempo varia conforme o modelo e o estado do equipamento. Essa estimativa é informada antes do serviço."),
            ("Como pedir orçamento?", "Envie pelo WhatsApp a quantidade, o modelo dos aparelhos e o bairro do atendimento."),
        ],
    },
    {
        "slug": "servicos/conserto",
        "keyword": "conserto de ar condicionado",
        "nome_curto": "Conserto",
        "servico_schema": "Conserto de ar condicionado",
        "title": "Conserto de Ar Condicionado em João Pessoa | EcoClima",
        "meta": "Conserto de ar condicionado em João Pessoa para todas as marcas: diagnóstico técnico, orçamento gratuito e 90 dias de garantia no reparo. Chame no WhatsApp.",
        "imagem": "conserto-ar-condicionado-joao-pessoa",
        "img_ratio": (1080, 1204),
        "img_alt": "Técnico da EcoClima fazendo conserto de ar condicionado em João Pessoa",
        "tagline": "Reparo especializado",
        "headline": "Conserto de ar condicionado em João Pessoa",
        "sub": "Conserto de ar condicionado especializado em João Pessoa e região, com diagnóstico técnico, orçamento claro e garantia do serviço.",
        "pains": [
            "Aparelho que liga mas não gela mais",
            "Pingando água dentro de casa ou do escritório",
            "Barulho estranho, vibração ou desligando sozinho",
            "Controle não responde ou códigos de erro no display",
            "Já chamou outro técnico e o problema voltou logo depois",
        ],
        "benefits": [
            "Atendimento rápido em toda João Pessoa",
            "Peças originais com garantia de fábrica",
            "Diagnóstico técnico transparente, sem enrolação",
            "Conserto de placas, compressores, capacitores e mais",
            "Orçamento gratuito e sem compromisso",
            "Garantia de 90 dias no reparo realizado",
        ],
        "steps": [
            ("Avaliação", "Nosso técnico identifica a falha e apresenta um orçamento claro antes de iniciar o reparo."),
            ("Reparo com peças originais", "Substituímos os componentes necessários utilizando peças de qualidade comprovada."),
            ("Testes e garantia", "Testamos o equipamento em funcionamento e fornecemos garantia formal do serviço."),
        ],
        "guarantee": "Todo conserto realizado pela EcoClima tem 90 dias de garantia formal. Se o mesmo defeito reaparecer nesse período, voltamos sem custo adicional.",
        "testimonials": [
            ("Fernando G.", "Bessa, João Pessoa", "Meu ar pingava muito. Identificaram a causa e resolveram no mesmo dia!"),
            ("Camila V.", "Aeroclube, João Pessoa", "Outro técnico tinha dito que precisava trocar tudo. Eles consertaram e ficou perfeito."),
            ("Diego A.", "Mangabeira, João Pessoa", "Atendimento honesto, preço justo e garantia. Recomendo de olhos fechados."),
        ],
        "sobre_titulo": "Conserto de ar condicionado que não gela, pinga ou dá erro",
        "sobre": [
            "O conserto de ar condicionado começa por um diagnóstico bem feito. Antes de trocar qualquer peça, o técnico da EcoClima identifica a causa da falha — gás, capacitor, placa eletrônica, sensor, compressor ou dreno entupido — e apresenta o orçamento para você aprovar.",
            "Consertamos ar condicionado split, inverter, cassete e piso-teto das principais marcas, em residências e empresas de João Pessoa e região. A maioria dos reparos é resolvida na mesma visita, e todo conserto sai com 90 dias de garantia formal.",
        ],
        "faqs": [
            ("Vocês consertam qualquer marca?", "Sim. Atendemos todas as principais marcas: LG, Samsung, Daikin, Midea, Electrolux, Springer, Consul, Elgin e outras."),
            ("Quanto tempo leva o conserto?", "A maioria dos reparos é resolvida na mesma visita. Casos que dependem de peças específicas podem levar de 1 a 3 dias úteis."),
            ("O orçamento é cobrado?", "Não. O orçamento é gratuito e sem compromisso. Você só paga se autorizar o conserto."),
            ("Qual a garantia do reparo?", "Oferecemos 90 dias de garantia formal sobre o serviço executado e sobre as peças trocadas."),
            ("E se o conserto não compensar?", "Somos transparentes. Se o conserto não for vantajoso, indicamos a troca e ajudamos você a decidir o melhor caminho."),
        ],
    },
    {
        "slug": "assistencia-tecnica-autorizada-ar-condicionado",
        "keyword": "assistência técnica autorizada de ar condicionado",
        "nome_curto": "Assistência técnica",
        "servico_schema": "Assistência técnica de ar condicionado",
        "title": "Assistência Técnica Autorizada de Ar Condicionado | EcoClima JP",
        "meta": "Assistência técnica autorizada de ar condicionado em João Pessoa: instalação, manutenção, limpeza e conserto de diversas marcas, com diagnóstico e garantia.",
        "imagem": "conserto-ar-condicionado-joao-pessoa",
        "img_ratio": (1080, 1204),
        "img_alt": "Assistência técnica de ar condicionado da EcoClima atendendo em João Pessoa",
        "tagline": "Assistência técnica autorizada",
        "headline": "Assistência técnica autorizada de ar condicionado em João Pessoa",
        "sub": "Atendimento especializado para instalação, manutenção e conserto de ar condicionado de diversas marcas em João Pessoa e região.",
        "pains": [
            "Dificuldade para encontrar assistência técnica autorizada na região",
            "Receio de perder a garantia por um serviço inadequado",
            "Equipamento apresentando falha, ruído ou baixo rendimento",
            "Necessidade de orientação técnica para sua marca e modelo",
            "Busca por atendimento local, claro e sem improvisos",
        ],
        "benefits": [
            "Assistência especializada para diversas marcas",
            "Atendimento em João Pessoa e região metropolitana",
            "Diagnóstico técnico antes da execução",
            "Instalação, manutenção e conserto",
            "Orientação clara sobre o serviço necessário",
            "Garantia formal do serviço realizado",
        ],
        "steps": [
            ("Informe a marca e o problema", "Envie pelo WhatsApp o modelo do aparelho e uma descrição do atendimento que precisa."),
            ("Avaliação especializada", "A equipe avalia o equipamento e apresenta a solução e o orçamento antes do serviço."),
            ("Serviço com garantia", "Executamos o atendimento técnico e testamos o funcionamento do ar condicionado."),
        ],
        "guarantee": "A EcoClima informa o diagnóstico, o serviço recomendado e as condições de garantia antes da execução, para você decidir com segurança.",
        "testimonials": [
            ("Mariana S.", "Manaíra, João Pessoa", "Recebi orientação clara desde o primeiro contato e o atendimento foi muito cuidadoso."),
            ("Carlos R.", "Bancários, João Pessoa", "A equipe identificou o problema do aparelho e explicou o serviço antes de começar."),
            ("Patrícia L.", "Altiplano, João Pessoa", "Atendimento pontual, técnico e organizado. Meu ar voltou a funcionar normalmente."),
        ],
        "sobre_titulo": "Assistência técnica de ar condicionado completa, em um só lugar",
        "sobre": [
            "Quem procura assistência técnica autorizada de ar condicionado quer duas coisas: resolver o problema e não correr risco com a garantia do aparelho. A EcoClima faz o diagnóstico antes de qualquer serviço, explica o que precisa ser feito e informa as condições de garantia antes de começar.",
            "Nossa assistência técnica cobre instalação, manutenção preventiva, limpeza e conserto de ar condicionado split, inverter, cassete e piso-teto de diversas marcas, em João Pessoa e região metropolitana. Envie a marca e o modelo pelo WhatsApp e confirmamos o atendimento do seu equipamento.",
        ],
        "faqs": [
            ("A EcoClima atende quais marcas?", "A EcoClima presta assistência especializada para diversas marcas. Envie a marca e o modelo pelo WhatsApp para confirmar o atendimento do seu equipamento."),
            ("Vocês atendem em João Pessoa?", "Sim. O atendimento cobre João Pessoa e a região metropolitana, conforme disponibilidade da equipe."),
            ("A assistência faz instalação e manutenção?", "Sim. A equipe realiza instalação, manutenção preventiva, limpeza e conserto de ar condicionado."),
            ("O serviço tem garantia?", "Sim. O prazo e as condições são informados conforme o tipo de serviço executado."),
            ("Como solicitar um orçamento?", "Clique no botão do WhatsApp e informe a marca, o modelo e o que está acontecendo com o equipamento."),
        ],
    },
]
